#!/usr/bin/env ruby

require "bundler/setup"
require 'optparse'
require 'stock_summary'

ticker, start_date = ARGV
ARGV << '-h' if !(ticker && start_date)

OptionParser.new do |opts|
  opts.banner = "Usage: stock_summary <ticker> <start_date> [options]"

  opts.on("-s S", String, "Specify Slack channel") do |s|
    StockSummary.configure.slack_channel = "\##{s}"
  end

  opts.on("-p N", Integer, "Number of digits after comma") do |n|
    StockSummary.configure.precision = n
  end

  opts.on_tail("-h", "--help", "Show this message") do
    puts opts
    exit
  end
end.parse!

StockSummary.get_stock_summary(ticker, start_date)
